#!/bin/bash

# allow 32-bit on 64-bit (x86) builds
if [ "$1" == "32" ]; then
    export CC=`which gcc`" -m32"
    export CXX=`which g++`" -m32"
    shift
    opt="--host=i686-pc-linux-gnu --target=i686-pc-linux-gnu"
fi

./autogen.sh || exit 1

chmod +x configure
./configure "$@" || exit 1
make -j3 || exit 1

